<a href="https://colab.research.google.com/github/nhwhite212/DealingwithDataSpring2021/blob/master/9-Big_data/9a-Interface_to_hive.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Big Data and Python  (UPDATED to work with python 3 and pyhive)
#NOTE, THE BIGDATA Clluster at Stern has been replaced by PEEL.HPC.NYU.EDU
### This is a much bigger cluster, but is not reachble from Google COLAB

Big Data clusters usually offer HIVE as an SQL like interface. This allows end-users who do not know how to write 
map-reduce code, or PIG or Java to manipulate files in the HDFS. The way they do this is to treat a folder of files as a table. Each file in the folder has to have the same structure. Typically, the folder contains files which are collected
over time, so every minute, hour, day another file is added. Users can then search, filter, join, merge the files using HQL, the HIVE QUERY LANGUAGE.

However, many analytical packages support remote access to Relational Data Bases. Examples being SAS, SPSS, R, Tableau, python, ...

Hive supports Hive server, which allows remote connections to HIVE, and allows remote execution of HQL commands. This allows a wide range of capabilities for analytical packages to use HIVE to do their back-end processing, and then pull the results to do analysis.

We will try to use this to  connect our IPYTHON  notebooks to the Stern big data cluster.

But first we need to install some software.
We need to install a package called pyhive and thrift_sasl

In [ ]:

!sudo apt-get install libsasl2-dev
!sudo pip install pyhs2
!sudo pip install pyhive
!sudo pip install thrift_sasl

Reading package lists... Done
Building dependency tree
Reading state information... Done
libsasl2-dev is already the newest version (2.1.27~101-g0780600+dfsg-3ubuntu2).
0 upgraded, 0 newly installed, 0 to remove and 82 not upgraded.
The directory '/home/nwhite/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/nwhite/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: pyhs2 in /usr/local/lib/python3.6/dist-packages (0.6.0)
Requirement already satisfied: sasl in /usr/local/lib/python3.6/dist-packages (from pyhs2) (0.2.1)
Requirement already satisfied: thrift in /usr/local/lib/python3.6/dist-packages (from pyhs2) (0.11.0)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from sasl->pyhs2) (1.11.0)
You are using pip version 10.0.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
The directory '/home/nwhite/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/nwhite/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: pyhive in /usr/local/lib/python3.6/dist-packages (0.6.1)
Requirement already satisfied: future in /usr/local/lib/python3.6/dist-packages (from pyhive) (0.17.1)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.6/dist-packages (from pyhive) (2.7.3)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil->pyhive) (1.11.0)
You are using pip version 10.0.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
The directory '/home/nwhite/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/nwhite/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: thrift_sasl in /usr/local/lib/python3.6/dist-packages (0.3.0)
Requirement already satisfied: sasl>=0.2.1 in /usr/local/lib/python3.6/dist-packages (from thrift_sasl) (0.2.1)
Requirement already satisfied: thrift>=0.10.0 in /usr/local/lib/python3.6/dist-packages (from thrift_sasl) (0.11.0)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from sasl>=0.2.1->thrift_sasl) (1.11.0)
You are using pip version 10.0.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

##  SUCCESS !!

##### Now we need to see how to connect to the Stern Bigdata  HIVE server. It runs on port 10000 on bigdata.stern.nyu.edu
##### Our hive server doesn't have any authentication, but you have to supply a userid and password anyway.
##### Note that it really isn't much different than querying a mysql data base.

#### Let's test with team 9's account, since there is no team 9, note we don't need a password.

In [ ]:
from pyhive import hive
cursor = hive.connect(host='bigdata.stern.nyu.edu',port=10000, username="DealingF17GB9",auth='NOSASL').cursor()
import pandas as pd
import sys
cursor.execute("show databases")
print("========== databases")
print(cursor.fetchall())
cursor.execute("use citibike")
print("===============Citibike tables ")
cursor.execute("show tables")
print(cursor.fetchall())
cursor.execute("describe formatted trips")
print(" trips fields  ")
print(cursor.fetchall())
cursor.execute("select * from trips limit 200")
print("=============================")
trips= cursor.fetchall()
dftrips=pd.DataFrame(trips)
print("trips table")
dftrips

========== databases
[('affordhouses',), ('b_spoke',), ('breakingfda',), ('cadms',), ('casino',), ('chris311',), ('citibike',), ('datagrp',), ('datajockeys',), ('dealing',), ('dealingf17gb5',), ('dealingf17gb9',), ('dealings2016',), ('default',), ('dsm348',), ('election',), ('fbook',), ('flightinformation',), ('gangkhargroup',), ('gn426',), ('gopaldatabase',), ('handofgod',), ('hh813',), ('insidejob',), ('jaf548',), ('jc4616',), ('jjk425',), ('kas747',), ('kick1',), ('kkw267',), ('lc3649',), ('mb3904',), ('met',), ('minnesota',), ('movement',), ('msba',), ('mtaturnstile',), ('muni',), ('munitest',), ('ngramdb',), ('ngramdb2',), ('nickhive',), ('nwhite',), ('piggi',), ('pjm419',), ('pricingpriceless',), ('recommender',), ('sastest',), ('sensordb',), ('sproject',), ('sr3085',), ('statechar',), ('strike',), ('sz649',), ('taq',), ('taxicab',), ('tca227',), ('team5',), ('team_dataguruz',), ('team_teamthatneversleeps',), ('teamjkn',), ('teamsalvos',), ('test',), ('testmsba',), ('themet',), ('tmpstrikes',), ('treecensus',), ('truck_pricing',), ('truckpricing',), ('vleda_logs',), ('xaxis',), ('yelp',), ('zillow',)]
===============Citibike tables
[('trips',)]
 trips fields
[('# col_name            ', 'data_type           ', 'comment             '), ('', None, None), ('tripduration', 'string', 'from deserializer'), ('starttime', 'string', 'from deserializer'), ('stoptime', 'string', 'from deserializer'), ('start_station_id', 'string', 'from deserializer'), ('start_station_name', 'string', 'from deserializer'), ('start_station_latitude', 'string', 'from deserializer'), ('start_station_longitude', 'string', 'from deserializer'), ('end_station_id', 'string', 'from deserializer'), ('end_station_name', 'string', 'from deserializer'), ('end_station_latitude', 'string', 'from deserializer'), ('end_station_longitude', 'string', 'from deserializer'), ('bikeid', 'string', 'from deserializer'), ('usertype', 'string', 'from deserializer'), ('birth_year', 'string', 'from deserializer'), ('gender', 'string', 'from deserializer'), ('', None, None), ('# Detailed Table Information', None, None), ('Database:           ', 'citibike            ', None), ('Owner:              ', 'pr1282              ', None), ('CreateTime:         ', 'Tue Nov 01 08:13:47 EDT 2016', None), ('LastAccessTime:     ', 'UNKNOWN             ', None), ('Protect Mode:       ', 'None                ', None), ('Retention:          ', '0                   ', None), ('Location:           ', 'hdfs://hadoop-name-node:54310/user/pr1282/citibike', None), ('Table Type:         ', 'EXTERNAL_TABLE      ', None), ('Table Parameters:', None, None), ('', 'COLUMN_STATS_ACCURATE', 'false               '), ('', 'EXTERNAL            ', 'TRUE                '), ('', 'numFiles            ', '0                   '), ('', 'numRows             ', '-1                  '), ('', 'rawDataSize         ', '-1                  '), ('', 'skip.header.line.count', '1                   '), ('', 'totalSize           ', '0                   '), ('', 'transient_lastDdlTime', '1478002427          '), ('', None, None), ('# Storage Information', None, None), ('SerDe Library:      ', 'org.apache.hadoop.hive.serde2.OpenCSVSerde', None), ('InputFormat:        ', 'org.apache.hadoop.mapred.TextInputFormat', None), ('OutputFormat:       ', 'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat', None), ('Compressed:         ', 'No                  ', None), ('Num Buckets:        ', '-1                  ', None), ('Bucket Columns:     ', '[]                  ', None), ('Sort Columns:       ', '[]                  ', None), ('Storage Desc Params:', None, None), ('', 'escapeChar          ', '\\\\                  '), ('', 'quoteChar           ', '\\"                  '), ('', 'separatorChar       ', ',                   '), ('', 'serialization.format', '1                   ')]
=============================
trips table

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,496,4/1/2016 00:00:26,4/1/2016 00:08:42,254,W 11 St & 6 Ave,40.73532427,-73.99800419,236,St Marks Pl & 2 Ave,40.7284186,-73.98713956,19704,Subscriber,1984,1
1,104,4/1/2016 00:00:27,4/1/2016 00:02:12,311,Norfolk St & Broome St,40.7172274,-73.98802084,350,Clinton St & Grand St,40.71559509,-73.9870295,21555,Subscriber,1970,1
2,128,4/1/2016 00:00:30,4/1/2016 00:02:38,3064,Myrtle Ave & Lewis Ave,40.69681963,-73.93756926,3059,Pulaski St & Marcus Garvey Blvd,40.6933982,-73.939877,17430,Subscriber,1986,1
3,1197,4/1/2016 00:00:34,4/1/2016 00:20:31,3156,E 72 St & York Ave,40.76663814,-73.95348296,490,8 Ave & W 33 St,40.751551,-73.993934,17413,Subscriber,1981,1
4,419,4/1/2016 00:00:46,4/1/2016 00:07:46,116,W 17 St & 8 Ave,40.74177603,-74.00149746,405,Washington St & Gansevoort St,40.739323,-74.008119,16714,Subscriber,1982,2
5,388,4/1/2016 00:00:59,4/1/2016 00:07:28,161,LaGuardia Pl & W 3 St,40.72917025,-73.99810231,326,E 11 St & 1 Ave,40.72953837,-73.98426726,19581,Subscriber,1996,1
6,558,4/1/2016 00:01:38,4/1/2016 00:10:56,453,W 22 St & 8 Ave,40.74475148,-73.99915362,161,LaGuardia Pl & W 3 St,40.72917025,-73.99810231,21125,Subscriber,1983,1
7,236,4/1/2016 00:01:38,4/1/2016 00:05:34,477,W 41 St & 8 Ave,40.75640548,-73.9900262,379,W 31 St & 7 Ave,40.749156,-73.9916,16677,Subscriber,1965,1
8,493,4/1/2016 00:01:40,4/1/2016 00:09:53,478,11 Ave & W 41 St,40.76030096,-73.99884222,459,W 20 St & 11 Ave,40.746745,-74.007756,18880,Subscriber,1977,1
9,1117,4/1/2016 00:01:48,4/1/2016 00:20:25,401,Allen St & Rivington St,40.72019576,-73.98997825,337,Old Slip & Front St,40.7037992,-74.00838676,21394,Subscriber,1981,1
10,379,4/1/2016 00:02:13,4/1/2016 00:08:33,521,8 Ave & W 31 St N,40.75096734871598,-73.99444207549095,470,W 20 St & 8 Ave,40.74345335,-74.00004031,16412,Subscriber,1980,2
11,236,4/1/2016 00:02:15,4/1/2016 00:06:12,3087,Metropolitan Ave & Meeker Ave,40.71413311,-73.95234386,3086,Graham Ave & Conselyea St,40.715143,-73.944507,15919,Subscriber,1990,1
12,429,4/1/2016 00:02:18,4/1/2016 00:09:27,546,E 30 St & Park Ave S,40.74444921,-73.98303529,501,FDR Drive & E 35 St,40.744219,-73.97121214,20828,Subscriber,1991,1
13,701,4/1/2016 00:02:25,4/1/2016 00:14:07,252,MacDougal St & Washington Sq,40.73226398,-73.99852205,393,E 5 St & Avenue C,40.72299208,-73.97995466,21003,Subscriber,1992,1
14,495,4/1/2016 00:02:26,4/1/2016 00:10:41,439,E 4 St & 2 Ave,40.7262807,-73.98978041,361,Allen St & Hester St,40.71605866,-73.99190759,15965,Subscriber,1969,1
15,501,4/1/2016 00:02:33,4/1/2016 00:10:54,174,E 25 St & 1 Ave,40.7381765,-73.97738662,394,E 9 St & Avenue C,40.72521311,-73.97768752,20944,Subscriber,1983,1
16,427,4/1/2016 00:02:44,4/1/2016 00:09:52,320,Leonard St & Church St,40.717571,-74.005549,161,LaGuardia Pl & W 3 St,40.72917025,-73.99810231,18775,Subscriber,1982,1
17,489,4/1/2016 00:02:47,4/1/2016 00:10:56,326,E 11 St & 1 Ave,40.72953837,-73.98426726,161,LaGuardia Pl & W 3 St,40.72917025,-73.99810231,15499,Subscriber,1981,2
18,450,4/1/2016 00:02:57,4/1/2016 00:10:27,312,Allen St & Stanton St,40.722055,-73.989111,2010,Grand St & Greene St,40.72165481,-74.00234737,21306,Subscriber,1983,1
19,116,4/1/2016 00:03:03,4/1/2016 00:05:00,307,Canal St & Rutgers St,40.71427487,-73.98990025,361,Allen St & Hester St,40.71605866,-73.99190759,16239,Subscriber,1988,1
20,186,4/1/2016 00:03:03,4/1/2016 00:06:10,307,Canal St & Rutgers St,40.71427487,-73.98990025,291,Madison St & Montgomery St,40.713126,-73.984844,19746,Subscriber,1965,1
21,258,4/1/2016 00:03:09,4/1/2016 00:07:28,435,W 21 St & 6 Ave,40.74173969,-73.99415556,462,W 22 St & 10 Ave,40.74691959,-74.00451887,23152,Subscriber,1983,1
22,217,4/1/2016 00:03:12,4/1/2016 00:06:50,249,Harrison St & Hudson St,40.71870987,-74.0090009,328,Watts St & Greenwich St,40.72405549,-74.00965965,21012,Subscriber,1984,1
23,454,4/1/2016 00:03:15,4/1/2016 00:10:49,161,LaGuardia Pl & W 3 St,40.72917025,-73.99810231,317,E 6 St & Avenue B,40.72453734,-73.98185424,19612,Subscriber,1989,1
24,1467,4/1/2016 00:03:21,4/1/2016 00:27:49,237,E 11 St & 2 Ave,40.73047309,-73.98672378,508,W 46 St & 11 Ave,40.76341379,-73.99667444,21166,Subscriber,1983,2
25,380,4/1/2016 00:03:45,4/1/2016 00:10:06,438,St Marks Pl & 1 Ave,40.72779126,-73.98564945,527,E 33 St & 2 Ave,40.744023,-73.976056,16813,Subscriber,1991,1
26,347,4/1/2016 00:04:04,4/1/2016 00:09:51,2010,Grand St & Greene St,40.72165481,-74.00234737,355,Bayard St & Baxter St,40.71602118,-73.99974372,21403,Subscriber,1975,1
27,222,4/1/2016 00:04:09,4/1/2016 00:07:52,383,Greenwich Ave & Charles St,40.735238,-74.000271,253,W 13 St & 5 Ave,40.73543934,-73.99453948,21507,Subscriber,1982,1
28,1434,4/1/2016 00:04:22,4/1/2016 00:28:17,442,W 27 St & 7 Ave,40.746647,-73.993915,439,E 4 St & 2 Ave,40.7262807,-73.98978041,17438,Subscriber,1994,1
29,435,4/1/2016 00:04:32,4/1/2016 00:11:48,475,E 16 St & Irving Pl,40.73524276,-73.98758561,445,E 10 St & Avenue A,40.72740794,-73.98142006,20517,Subscriber,1995,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170,633,4/1/2016 00:29:06,4/1/2016 00:39:39,285,Broadway & E 14 St,40.73454567,-73.99074142,536,1 Ave & E 30 St,40.74144387,-73.97536082,15685,Subscriber,1991,1
171,166,4/1/2016 00:29:15,4/1/2016 00:32:02,433,E 13 St & Avenue A,40.72955361,-73.98057249,317,E 6 St & Avenue B,40.72453734,-73.98185424,16870,Subscriber,1992,1
172,421,4/1/2016 00:29:58,4/1/2016 00:36:59,402,Broadway & E 22 St,40.7403432,-73.98955109,284,Greenwich Ave & 8 Ave,40.7390169121,-74.0026376103,21444,Subscriber,1991,1
173,619,4/1/2016 00:30:15,4/1/2016 00:40:34,3064,Myrtle Ave & Lewis Ave,40.69681963,-73.93756926,3048,Putnam Ave & Nostrand Ave,40.68402,-73.94977,19891,Subscriber,1989,2
174,365,4/1/2016 00:30:24,4/1/2016 00:36:29,296,Division St & Bowery,40.71413089,-73.9970468,348,W Broadway & Spring St,40.72490985,-74.00154702,20551,Subscriber,1992,1
175,703,4/1/2016 00:30:29,4/1/2016 00:42:12,238,Bank St & Washington St,40.7361967,-74.00859207,265,Stanton St & Chrystie St,40.72229346,-73.99147535,18433,Subscriber,1965,1
176,288,4/1/2016 00:31:37,4/1/2016 00:36:26,346,Bank St & Hudson St,40.73652889,-74.00618026,470,W 20 St & 8 Ave,40.74345335,-74.00004031,14707,Customer,,0
177,467,4/1/2016 00:31:40,4/1/2016 00:39:28,336,Sullivan St & Washington Sq,40.73047747,-73.99906065,254,W 11 St & 6 Ave,40.73532427,-73.99800419,15991,Customer,,0
178,654,4/1/2016 00:31:58,4/1/2016 00:42:53,483,E 12 St & 3 Ave,40.73223272,-73.98889957,308,St James Pl & Oliver St,40.71307916,-73.99851193,21713,Subscriber,1964,1
179,300,4/1/2016 00:32:09,4/1/2016 00:37:10,328,Watts St & Greenwich St,40.72405549,-74.00965965,320,Leonard St & Church St,40.717571,-74.005549,20226,Subscriber,1993,1
180,603,4/1/2016 00:32:37,4/1/2016 00:42:40,433,E 13 St & Avenue A,40.72955361,-73.98057249,540,Lexington Ave & E 29 St,40.74311555376486,-73.98215353488922,23291,Subscriber,1975,1
181,433,4/1/2016 00:32:38,4/1/2016 00:39:52,430,York St & Jay St,40.7014851,-73.98656928,242,Carlton Ave & Flushing Ave,40.697787,-73.973736,15758,Subscriber,1960,1
182,218,4/1/2016 00:32:40,4/1/2016 00:36:19,3055,Greene Ave & Nostrand Ave,40.6883337,-73.950916,437,Macon St & Nostrand Ave,40.6809833854,-73.9500479759,21458,Subscriber,1979,1
183,419,4/1/2016 00:32:46,4/1/2016 00:39:46,312,Allen St & Stanton St,40.722055,-73.989111,350,Clinton St & Grand St,40.71559509,-73.9870295,21452,Subscriber,1973,1
184,998,4/1/2016 00:32:50,4/1/2016 00:49:29,3134,3 Ave & E 62 St,40.76312584,-73.96526895,540,Lexington Ave & E 29 St,40.74311555376486,-73.98215353488922,17851,Subscriber,1986,1
185,489,4/1/2016 00:32:58,4/1/2016 00:41:07,494,W 26 St & 8 Ave,40.74734825,-73.99723551,450,W 49 St & 8 Ave,40.76227205,-73.98788205,17881,Subscriber,1978,1
186,1212,4/1/2016 00:33:29,4/1/2016 00:53:41,358,Christopher St & Greenwich St,40.73291553,-74.00711384,317,E 6 St & Avenue B,40.72453734,-73.98185424,19345,Subscriber,1963,1
187,11939,4/1/2016 00:33:31,4/1/2016 03:52:31,3110,Meserole Ave & Manhattan Ave,40.72708584,-73.95299117,3109,Banker St & Meserole Ave,40.72606,-73.95621,15784,Subscriber,1991,1
188,2129,4/1/2016 00:34:17,4/1/2016 01:09:46,478,11 Ave & W 41 St,40.76030096,-73.99884222,282,Kent Ave & S 11 St,40.707644944175705,-73.96841526031494,17465,Subscriber,1988,1
189,1121,4/1/2016 00:34:23,4/1/2016 00:53:04,540,Lexington Ave & E 29 St,40.74311555376486,-73.98215353488922,3161,W 76 St & Columbus Ave,40.7801839724239,-73.97728532552719,17116,Subscriber,1980,1
190,254,4/1/2016 00:34:47,4/1/2016 00:39:01,3096,Union Ave & N 12 St,40.71924,-73.95242,471,Grand St & Havemeyer St,40.71286844,-73.95698119,15807,Subscriber,1987,1
191,2192,4/1/2016 00:34:53,4/1/2016 01:11:26,307,Canal St & Rutgers St,40.71427487,-73.98990025,266,Avenue D & E 8 St,40.72368361,-73.97574813,14633,Subscriber,1997,1
192,355,4/1/2016 00:35:18,4/1/2016 00:41:14,504,1 Ave & E 15 St,40.73221853,-73.98165557,345,W 13 St & 6 Ave,40.73649403,-73.99704374,21175,Subscriber,1986,1
193,373,4/1/2016 00:35:18,4/1/2016 00:41:31,439,E 4 St & 2 Ave,40.7262807,-73.98978041,301,E 2 St & Avenue B,40.72217444,-73.98368779,16489,Subscriber,1980,1
194,368,4/1/2016 00:35:20,4/1/2016 00:41:29,439,E 4 St & 2 Ave,40.7262807,-73.98978041,301,E 2 St & Avenue B,40.72217444,-73.98368779,15846,Subscriber,1990,2
195,857,4/1/2016 00:35:21,4/1/2016 00:49:39,354,Emerson Pl & Myrtle Ave,40.69363137,-73.96223558,471,Grand St & Havemeyer St,40.71286844,-73.95698119,18719,Subscriber,1979,1
196,719,4/1/2016 00:35:34,4/1/2016 00:47:33,402,Broadway & E 22 St,40.7403432,-73.98955109,411,E 6 St & Avenue D,40.72228087,-73.97668709,21679,Subscriber,1991,1
197,1743,4/1/2016 00:35:36,4/1/2016 01:04:39,477,W 41 St & 8 Ave,40.75640548,-73.9900262,264,Maiden Ln & Pearl St,40.70706456,-74.00731853,20324,Subscriber,1992,2
198,859,4/1/2016 00:35:49,4/1/2016 00:50:09,167,E 39 St & 3 Ave,40.7489006,-73.97604882,483,E 12 St & 3 Ave,40.73223272,-73.98889957,15773,Customer,,0
199,1510,4/1/2016 00:35:54,4/1/2016 01:01:04,426,West St & Chambers St,40.71754834,-74.01322069,529,W 42 St & 8 Ave,40.7575699,-73.99098507,20833,Subscriber,1986,1

## And there we have it. We can access data in our bigdata server directly from python.
### You can load data into the HDFS, and then access it from a python notebook.

In [ ]:
from pyhive import hive
cursor = hive.connect(host='bigdata.stern.nyu.edu',port=10000, username="DealingF1GB10",auth='NOSASL').cursor()
import pandas as pd
import sys
cursor.execute("show databases")
print("========== databases")
print(cursor.fetchall())
cursor.execute("use citibike")
print("===============Citibike tables ")
cursor.execute("show tables")
print(cursor.fetchall())
cursor.execute("describe formatted trips")
print(" trips fields  ")
print(cursor.fetchall())
cursor.execute("select * from trips limit 200")
print("=============================")
trips= cursor.fetchall()
dftrips=pd.DataFrame(trips)
print("trips table")
dftrips

========== databases
[('affordhouses',), ('b_spoke',), ('breakingfda',), ('cadms',), ('casino',), ('chris311',), ('citibike',), ('datagrp',), ('datajockeys',), ('dealing',), ('dealingf17gb5',), ('dealingf17gb9',), ('dealings2016',), ('default',), ('dsm348',), ('election',), ('fbook',), ('flightinformation',), ('gangkhargroup',), ('gn426',), ('gopaldatabase',), ('handofgod',), ('hh813',), ('insidejob',), ('jaf548',), ('jc4616',), ('jjk425',), ('kas747',), ('kick1',), ('kkw267',), ('lc3649',), ('mb3904',), ('met',), ('minnesota',), ('movement',), ('msba',), ('mtaturnstile',), ('muni',), ('munitest',), ('ngramdb',), ('ngramdb2',), ('nickhive',), ('nwhite',), ('piggi',), ('pjm419',), ('pricingpriceless',), ('recommender',), ('sastest',), ('sensordb',), ('sproject',), ('sr3085',), ('statechar',), ('strike',), ('sz649',), ('taq',), ('taxicab',), ('tca227',), ('team5',), ('team_dataguruz',), ('team_teamthatneversleeps',), ('teamjkn',), ('teamsalvos',), ('test',), ('testmsba',), ('themet',), ('tmpstrikes',), ('treecensus',), ('truck_pricing',), ('truckpricing',), ('vleda_logs',), ('xaxis',), ('yelp',), ('zillow',)]
===============Citibike tables
[('trips',)]
 trips fields
[('# col_name            ', 'data_type           ', 'comment             '), ('', None, None), ('tripduration', 'string', 'from deserializer'), ('starttime', 'string', 'from deserializer'), ('stoptime', 'string', 'from deserializer'), ('start_station_id', 'string', 'from deserializer'), ('start_station_name', 'string', 'from deserializer'), ('start_station_latitude', 'string', 'from deserializer'), ('start_station_longitude', 'string', 'from deserializer'), ('end_station_id', 'string', 'from deserializer'), ('end_station_name', 'string', 'from deserializer'), ('end_station_latitude', 'string', 'from deserializer'), ('end_station_longitude', 'string', 'from deserializer'), ('bikeid', 'string', 'from deserializer'), ('usertype', 'string', 'from deserializer'), ('birth_year', 'string', 'from deserializer'), ('gender', 'string', 'from deserializer'), ('', None, None), ('# Detailed Table Information', None, None), ('Database:           ', 'citibike            ', None), ('Owner:              ', 'pr1282              ', None), ('CreateTime:         ', 'Tue Nov 01 08:13:47 EDT 2016', None), ('LastAccessTime:     ', 'UNKNOWN             ', None), ('Protect Mode:       ', 'None                ', None), ('Retention:          ', '0                   ', None), ('Location:           ', 'hdfs://hadoop-name-node:54310/user/pr1282/citibike', None), ('Table Type:         ', 'EXTERNAL_TABLE      ', None), ('Table Parameters:', None, None), ('', 'COLUMN_STATS_ACCURATE', 'false               '), ('', 'EXTERNAL            ', 'TRUE                '), ('', 'numFiles            ', '0                   '), ('', 'numRows             ', '-1                  '), ('', 'rawDataSize         ', '-1                  '), ('', 'skip.header.line.count', '1                   '), ('', 'totalSize           ', '0                   '), ('', 'transient_lastDdlTime', '1478002427          '), ('', None, None), ('# Storage Information', None, None), ('SerDe Library:      ', 'org.apache.hadoop.hive.serde2.OpenCSVSerde', None), ('InputFormat:        ', 'org.apache.hadoop.mapred.TextInputFormat', None), ('OutputFormat:       ', 'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat', None), ('Compressed:         ', 'No                  ', None), ('Num Buckets:        ', '-1                  ', None), ('Bucket Columns:     ', '[]                  ', None), ('Sort Columns:       ', '[]                  ', None), ('Storage Desc Params:', None, None), ('', 'escapeChar          ', '\\\\                  '), ('', 'quoteChar           ', '\\"                  '), ('', 'separatorChar       ', ',                   '), ('', 'serialization.format', '1                   ')]
=============================
trips table

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,496,4/1/2016 00:00:26,4/1/2016 00:08:42,254,W 11 St & 6 Ave,40.73532427,-73.99800419,236,St Marks Pl & 2 Ave,40.7284186,-73.98713956,19704,Subscriber,1984,1
1,104,4/1/2016 00:00:27,4/1/2016 00:02:12,311,Norfolk St & Broome St,40.7172274,-73.98802084,350,Clinton St & Grand St,40.71559509,-73.9870295,21555,Subscriber,1970,1
2,128,4/1/2016 00:00:30,4/1/2016 00:02:38,3064,Myrtle Ave & Lewis Ave,40.69681963,-73.93756926,3059,Pulaski St & Marcus Garvey Blvd,40.6933982,-73.939877,17430,Subscriber,1986,1
3,1197,4/1/2016 00:00:34,4/1/2016 00:20:31,3156,E 72 St & York Ave,40.76663814,-73.95348296,490,8 Ave & W 33 St,40.751551,-73.993934,17413,Subscriber,1981,1
4,419,4/1/2016 00:00:46,4/1/2016 00:07:46,116,W 17 St & 8 Ave,40.74177603,-74.00149746,405,Washington St & Gansevoort St,40.739323,-74.008119,16714,Subscriber,1982,2
5,388,4/1/2016 00:00:59,4/1/2016 00:07:28,161,LaGuardia Pl & W 3 St,40.72917025,-73.99810231,326,E 11 St & 1 Ave,40.72953837,-73.98426726,19581,Subscriber,1996,1
6,558,4/1/2016 00:01:38,4/1/2016 00:10:56,453,W 22 St & 8 Ave,40.74475148,-73.99915362,161,LaGuardia Pl & W 3 St,40.72917025,-73.99810231,21125,Subscriber,1983,1
7,236,4/1/2016 00:01:38,4/1/2016 00:05:34,477,W 41 St & 8 Ave,40.75640548,-73.9900262,379,W 31 St & 7 Ave,40.749156,-73.9916,16677,Subscriber,1965,1
8,493,4/1/2016 00:01:40,4/1/2016 00:09:53,478,11 Ave & W 41 St,40.76030096,-73.99884222,459,W 20 St & 11 Ave,40.746745,-74.007756,18880,Subscriber,1977,1
9,1117,4/1/2016 00:01:48,4/1/2016 00:20:25,401,Allen St & Rivington St,40.72019576,-73.98997825,337,Old Slip & Front St,40.7037992,-74.00838676,21394,Subscriber,1981,1
10,379,4/1/2016 00:02:13,4/1/2016 00:08:33,521,8 Ave & W 31 St N,40.75096734871598,-73.99444207549095,470,W 20 St & 8 Ave,40.74345335,-74.00004031,16412,Subscriber,1980,2
11,236,4/1/2016 00:02:15,4/1/2016 00:06:12,3087,Metropolitan Ave & Meeker Ave,40.71413311,-73.95234386,3086,Graham Ave & Conselyea St,40.715143,-73.944507,15919,Subscriber,1990,1
12,429,4/1/2016 00:02:18,4/1/2016 00:09:27,546,E 30 St & Park Ave S,40.74444921,-73.98303529,501,FDR Drive & E 35 St,40.744219,-73.97121214,20828,Subscriber,1991,1
13,701,4/1/2016 00:02:25,4/1/2016 00:14:07,252,MacDougal St & Washington Sq,40.73226398,-73.99852205,393,E 5 St & Avenue C,40.72299208,-73.97995466,21003,Subscriber,1992,1
14,495,4/1/2016 00:02:26,4/1/2016 00:10:41,439,E 4 St & 2 Ave,40.7262807,-73.98978041,361,Allen St & Hester St,40.71605866,-73.99190759,15965,Subscriber,1969,1
15,501,4/1/2016 00:02:33,4/1/2016 00:10:54,174,E 25 St & 1 Ave,40.7381765,-73.97738662,394,E 9 St & Avenue C,40.72521311,-73.97768752,20944,Subscriber,1983,1
16,427,4/1/2016 00:02:44,4/1/2016 00:09:52,320,Leonard St & Church St,40.717571,-74.005549,161,LaGuardia Pl & W 3 St,40.72917025,-73.99810231,18775,Subscriber,1982,1
17,489,4/1/2016 00:02:47,4/1/2016 00:10:56,326,E 11 St & 1 Ave,40.72953837,-73.98426726,161,LaGuardia Pl & W 3 St,40.72917025,-73.99810231,15499,Subscriber,1981,2
18,450,4/1/2016 00:02:57,4/1/2016 00:10:27,312,Allen St & Stanton St,40.722055,-73.989111,2010,Grand St & Greene St,40.72165481,-74.00234737,21306,Subscriber,1983,1
19,116,4/1/2016 00:03:03,4/1/2016 00:05:00,307,Canal St & Rutgers St,40.71427487,-73.98990025,361,Allen St & Hester St,40.71605866,-73.99190759,16239,Subscriber,1988,1
20,186,4/1/2016 00:03:03,4/1/2016 00:06:10,307,Canal St & Rutgers St,40.71427487,-73.98990025,291,Madison St & Montgomery St,40.713126,-73.984844,19746,Subscriber,1965,1
21,258,4/1/2016 00:03:09,4/1/2016 00:07:28,435,W 21 St & 6 Ave,40.74173969,-73.99415556,462,W 22 St & 10 Ave,40.74691959,-74.00451887,23152,Subscriber,1983,1
22,217,4/1/2016 00:03:12,4/1/2016 00:06:50,249,Harrison St & Hudson St,40.71870987,-74.0090009,328,Watts St & Greenwich St,40.72405549,-74.00965965,21012,Subscriber,1984,1
23,454,4/1/2016 00:03:15,4/1/2016 00:10:49,161,LaGuardia Pl & W 3 St,40.72917025,-73.99810231,317,E 6 St & Avenue B,40.72453734,-73.98185424,19612,Subscriber,1989,1
24,1467,4/1/2016 00:03:21,4/1/2016 00:27:49,237,E 11 St & 2 Ave,40.73047309,-73.98672378,508,W 46 St & 11 Ave,40.76341379,-73.99667444,21166,Subscriber,1983,2
25,380,4/1/2016 00:03:45,4/1/2016 00:10:06,438,St Marks Pl & 1 Ave,40.72779126,-73.98564945,527,E 33 St & 2 Ave,40.744023,-73.976056,16813,Subscriber,1991,1
26,347,4/1/2016 00:04:04,4/1/2016 00:09:51,2010,Grand St & Greene St,40.72165481,-74.00234737,355,Bayard St & Baxter St,40.71602118,-73.99974372,21403,Subscriber,1975,1
27,222,4/1/2016 00:04:09,4/1/2016 00:07:52,383,Greenwich Ave & Charles St,40.735238,-74.000271,253,W 13 St & 5 Ave,40.73543934,-73.99453948,21507,Subscriber,1982,1
28,1434,4/1/2016 00:04:22,4/1/2016 00:28:17,442,W 27 St & 7 Ave,40.746647,-73.993915,439,E 4 St & 2 Ave,40.7262807,-73.98978041,17438,Subscriber,1994,1
29,435,4/1/2016 00:04:32,4/1/2016 00:11:48,475,E 16 St & Irving Pl,40.73524276,-73.98758561,445,E 10 St & Avenue A,40.72740794,-73.98142006,20517,Subscriber,1995,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170,633,4/1/2016 00:29:06,4/1/2016 00:39:39,285,Broadway & E 14 St,40.73454567,-73.99074142,536,1 Ave & E 30 St,40.74144387,-73.97536082,15685,Subscriber,1991,1
171,166,4/1/2016 00:29:15,4/1/2016 00:32:02,433,E 13 St & Avenue A,40.72955361,-73.98057249,317,E 6 St & Avenue B,40.72453734,-73.98185424,16870,Subscriber,1992,1
172,421,4/1/2016 00:29:58,4/1/2016 00:36:59,402,Broadway & E 22 St,40.7403432,-73.98955109,284,Greenwich Ave & 8 Ave,40.7390169121,-74.0026376103,21444,Subscriber,1991,1
173,619,4/1/2016 00:30:15,4/1/2016 00:40:34,3064,Myrtle Ave & Lewis Ave,40.69681963,-73.93756926,3048,Putnam Ave & Nostrand Ave,40.68402,-73.94977,19891,Subscriber,1989,2
174,365,4/1/2016 00:30:24,4/1/2016 00:36:29,296,Division St & Bowery,40.71413089,-73.9970468,348,W Broadway & Spring St,40.72490985,-74.00154702,20551,Subscriber,1992,1
175,703,4/1/2016 00:30:29,4/1/2016 00:42:12,238,Bank St & Washington St,40.7361967,-74.00859207,265,Stanton St & Chrystie St,40.72229346,-73.99147535,18433,Subscriber,1965,1
176,288,4/1/2016 00:31:37,4/1/2016 00:36:26,346,Bank St & Hudson St,40.73652889,-74.00618026,470,W 20 St & 8 Ave,40.74345335,-74.00004031,14707,Customer,,0
177,467,4/1/2016 00:31:40,4/1/2016 00:39:28,336,Sullivan St & Washington Sq,40.73047747,-73.99906065,254,W 11 St & 6 Ave,40.73532427,-73.99800419,15991,Customer,,0
178,654,4/1/2016 00:31:58,4/1/2016 00:42:53,483,E 12 St & 3 Ave,40.73223272,-73.98889957,308,St James Pl & Oliver St,40.71307916,-73.99851193,21713,Subscriber,1964,1
179,300,4/1/2016 00:32:09,4/1/2016 00:37:10,328,Watts St & Greenwich St,40.72405549,-74.00965965,320,Leonard St & Church St,40.717571,-74.005549,20226,Subscriber,1993,1
180,603,4/1/2016 00:32:37,4/1/2016 00:42:40,433,E 13 St & Avenue A,40.72955361,-73.98057249,540,Lexington Ave & E 29 St,40.74311555376486,-73.98215353488922,23291,Subscriber,1975,1
181,433,4/1/2016 00:32:38,4/1/2016 00:39:52,430,York St & Jay St,40.7014851,-73.98656928,242,Carlton Ave & Flushing Ave,40.697787,-73.973736,15758,Subscriber,1960,1
182,218,4/1/2016 00:32:40,4/1/2016 00:36:19,3055,Greene Ave & Nostrand Ave,40.6883337,-73.950916,437,Macon St & Nostrand Ave,40.6809833854,-73.9500479759,21458,Subscriber,1979,1
183,419,4/1/2016 00:32:46,4/1/2016 00:39:46,312,Allen St & Stanton St,40.722055,-73.989111,350,Clinton St & Grand St,40.71559509,-73.9870295,21452,Subscriber,1973,1
184,998,4/1/2016 00:32:50,4/1/2016 00:49:29,3134,3 Ave & E 62 St,40.76312584,-73.96526895,540,Lexington Ave & E 29 St,40.74311555376486,-73.98215353488922,17851,Subscriber,1986,1
185,489,4/1/2016 00:32:58,4/1/2016 00:41:07,494,W 26 St & 8 Ave,40.74734825,-73.99723551,450,W 49 St & 8 Ave,40.76227205,-73.98788205,17881,Subscriber,1978,1
186,1212,4/1/2016 00:33:29,4/1/2016 00:53:41,358,Christopher St & Greenwich St,40.73291553,-74.00711384,317,E 6 St & Avenue B,40.72453734,-73.98185424,19345,Subscriber,1963,1
187,11939,4/1/2016 00:33:31,4/1/2016 03:52:31,3110,Meserole Ave & Manhattan Ave,40.72708584,-73.95299117,3109,Banker St & Meserole Ave,40.72606,-73.95621,15784,Subscriber,1991,1
188,2129,4/1/2016 00:34:17,4/1/2016 01:09:46,478,11 Ave & W 41 St,40.76030096,-73.99884222,282,Kent Ave & S 11 St,40.707644944175705,-73.96841526031494,17465,Subscriber,1988,1
189,1121,4/1/2016 00:34:23,4/1/2016 00:53:04,540,Lexington Ave & E 29 St,40.74311555376486,-73.98215353488922,3161,W 76 St & Columbus Ave,40.7801839724239,-73.97728532552719,17116,Subscriber,1980,1
190,254,4/1/2016 00:34:47,4/1/2016 00:39:01,3096,Union Ave & N 12 St,40.71924,-73.95242,471,Grand St & Havemeyer St,40.71286844,-73.95698119,15807,Subscriber,1987,1
191,2192,4/1/2016 00:34:53,4/1/2016 01:11:26,307,Canal St & Rutgers St,40.71427487,-73.98990025,266,Avenue D & E 8 St,40.72368361,-73.97574813,14633,Subscriber,1997,1
192,355,4/1/2016 00:35:18,4/1/2016 00:41:14,504,1 Ave & E 15 St,40.73221853,-73.98165557,345,W 13 St & 6 Ave,40.73649403,-73.99704374,21175,Subscriber,1986,1
193,373,4/1/2016 00:35:18,4/1/2016 00:41:31,439,E 4 St & 2 Ave,40.7262807,-73.98978041,301,E 2 St & Avenue B,40.72217444,-73.98368779,16489,Subscriber,1980,1
194,368,4/1/2016 00:35:20,4/1/2016 00:41:29,439,E 4 St & 2 Ave,40.7262807,-73.98978041,301,E 2 St & Avenue B,40.72217444,-73.98368779,15846,Subscriber,1990,2
195,857,4/1/2016 00:35:21,4/1/2016 00:49:39,354,Emerson Pl & Myrtle Ave,40.69363137,-73.96223558,471,Grand St & Havemeyer St,40.71286844,-73.95698119,18719,Subscriber,1979,1
196,719,4/1/2016 00:35:34,4/1/2016 00:47:33,402,Broadway & E 22 St,40.7403432,-73.98955109,411,E 6 St & Avenue D,40.72228087,-73.97668709,21679,Subscriber,1991,1
197,1743,4/1/2016 00:35:36,4/1/2016 01:04:39,477,W 41 St & 8 Ave,40.75640548,-73.9900262,264,Maiden Ln & Pearl St,40.70706456,-74.00731853,20324,Subscriber,1992,2
198,859,4/1/2016 00:35:49,4/1/2016 00:50:09,167,E 39 St & 3 Ave,40.7489006,-73.97604882,483,E 12 St & 3 Ave,40.73223272,-73.98889957,15773,Customer,,0
199,1510,4/1/2016 00:35:54,4/1/2016 01:01:04,426,West St & Chambers St,40.71754834,-74.01322069,529,W 42 St & 8 Ave,40.7575699,-73.99098507,20833,Subscriber,1986,1

In [ ]:
# Lets look at the yelp data
cursor.execute('use yelp')
cursor.execute('show tables')
print(cursor.fetchall())

[('businesses',), ('busstate',), ('restaurants',), ('reviews',), ('v_reviews',)]

In [ ]:
cursor.execute('describe businesses')
print(cursor.fetchall())

[('json', 'string', '')]

In [ ]:
cursor.execute('select * from businesses limit 2')
print(cursor.fetchall())

[('{"business_id":"Apn5Q_b6Nz61Tq4XzPdf9A","name":"Minhas Micro Brewery","neighborhood":"","address":"1314 44 Avenue NE","city":"Calgary","state":"AB","postal_code":"T2E 6L6","latitude":51.0918130155,"longitude":-114.031674872,"stars":4.0,"review_count":24,"is_open":1,"attributes":{"BikeParking":"False","BusinessAcceptsCreditCards":"True","BusinessParking":"{\'garage\': False, \'street\': True, \'validated\': False, \'lot\': False, \'valet\': False}","GoodForKids":"True","HasTV":"True","NoiseLevel":"average","OutdoorSeating":"False","RestaurantsAttire":"casual","RestaurantsDelivery":"False","RestaurantsGoodForGroups":"True","RestaurantsPriceRange2":"2","RestaurantsReservations":"True","RestaurantsTakeOut":"True"},"categories":"Tours, Breweries, Pizza, Restaurants, Food, Hotels & Travel","hours":{"Monday":"8:30-17:0","Tuesday":"11:0-21:0","Wednesday":"11:0-21:0","Thursday":"11:0-21:0","Friday":"11:0-21:0","Saturday":"11:0-21:0"}}',), ('{"business_id":"AjEbIBw6ZFfln7ePHha9PA","name":"CK\'S BBQ & Catering","neighborhood":"","address":"","city":"Henderson","state":"NV","postal_code":"89002","latitude":35.9607337,"longitude":-114.939821,"stars":4.5,"review_count":3,"is_open":0,"attributes":{"Alcohol":"none","BikeParking":"False","BusinessAcceptsCreditCards":"True","BusinessParking":"{\'garage\': False, \'street\': True, \'validated\': False, \'lot\': True, \'valet\': False}","Caters":"True","DogsAllowed":"True","DriveThru":"False","GoodForKids":"True","GoodForMeal":"{\'dessert\': False, \'latenight\': False, \'lunch\': False, \'dinner\': False, \'breakfast\': False, \'brunch\': False}","HasTV":"False","OutdoorSeating":"True","RestaurantsAttire":"casual","RestaurantsDelivery":"False","RestaurantsGoodForGroups":"True","RestaurantsPriceRange2":"2","RestaurantsReservations":"False","RestaurantsTableService":"False","RestaurantsTakeOut":"True","WheelchairAccessible":"True","WiFi":"no"},"categories":"Chicken Wings, Burgers, Caterers, Street Vendors, Barbeque, Food Trucks, Food, Restaurants, Event Planning & Services","hours":{"Friday":"17:0-23:0","Saturday":"17:0-23:0","Sunday":"17:0-23:0"}}',)]

In [ ]:
cursor.execute("select get_json_object(json,'$.business_id') from businesses limit 5")
print(cursor.fetchall())

[('Apn5Q_b6Nz61Tq4XzPdf9A',), ('AjEbIBw6ZFfln7ePHha9PA',), ('O8S5hYJ1SMc8fA4QBtVujA',), ('bFzdJJ3wp3PZssNEsyU23g',), ('8USyCYqpScwiNEb58Bt6CA',)]

###### Lets look at NY

In [ ]:
cursor.execute("select get_json_object(json,'$.business_id') from businesses where get_json_object(json,'$.state') ='NY' ")
print(cursor.fetchall())

[('BmZu5ackYYCrgQIaJ3-r9A',), ('f5Pg89x-2xek78E9KHMhNg',), ('NVsv96we6iTkEClbSlWd5A',), ('jH19V2I9fIslnNhDzPmdkA',), ('-Rw3wxbeHhZy6SURriXZ8g',), ('2Gc0f44JbkQBMoImlhDf9g',), ('Ya-HZZrzMWYSBtGyLajDQg',), ('LbM7p-cI0dUCkaUzOyFMTw',), ('6ipr7nnwrzf_o3MGD-8nlA',), ('V-uUDuDnUMqUWPjNULqPOA',), ('M8v5TVWQu-mw6Qn3SPc1aQ',), ('0oyzNutZ--rBqP_boeegPg',), ('3lFUdYf2zfFxrm8LIpupBw',), ('6029Vtm4LVYGPLm00htXrQ',), ('xkha6iK_PLsUqnFB-CJW5g',), ('sY2TrIpQaS8kFDI8GRGS3Q',), ('Uz77JHl5e6zlGa-71-6_dA',), ('SMx-Ltydt4Y4JFoSfheOhA',), ('-37cHdR8Z4Qrql6b6VoB9w',)]

#### busbystate is a table created with hive on bigdata, it has total counts by state
#### pyhive seems to have a problem with views..

In [ ]:
cursor.execute("select * from busbystate")
busbystate= cursor.fetchall()
busdf=pd.DataFrame(busbystate)
busdf

        0    1
0      11   01
1       1   10
2       1   11
3       1    4
4       1   45
5       3    6
6    7670   AB
7       1   AG
8       2   AL
9       2   AR
10  56495   AZ
11      2    B
12      1   BC
13     60   BY
14     34    C
15      8   CA
16      1   CC
17      2  CMA
18     43   CO
19      1  CRF
20      1   CS
21      1   DE
22      1   FL
23      2    G
24      1   GA
25     32   HE
26      1   HH
27      1   HU
28   1937   IL
29    101   IN
..    ...  ...
39    134   NI
40     23  NLK
41  35688   NV
42      4   NW
43     19   NY
44    163  NYK
45      3    O
46  13664   OH
47  32393   ON
48     72   OR
49  10966   PA
50      1   PO
51   8756   QC
52      1  RCC
53     19   RP
54    770   SC
55      2   SG
56      1   SP
57     45   ST
58      1  TAM
59      1    V
60      1   VA
61      7   VS
62      2   VT
63      2   WA
64      1  WAR
65      1  WHT
66   5042   WI
67     23  XGM
68      1  XMS

[69 rows x 2 columns]

## So, takeaway is use a bigdata cluster for high level  of very large data sets, 
##and then pull data 

### into an easier to use environment like pandas, tableau, excel, R, ...